### ISSUE TITLE
[request] webview tabs

### ISSUE THREAD

**Issue by nativescriptxamarin** [AVnetWS/Hentoid#111]
In hitomi, we should get lists of result and find, and arrange them per every search we do, on client side.
And that's fine on pc, but requiring so much times on mobile device.
So I would like to keep finished searching page, and browse some comics that I want to see via other internet tabs.
Is it possible to achieve? If we can't i suggest you to use any other browser and use their 'url share' function to deal just comic's url on hentoid, and download it.
Anyway thanks for making this awesome app and maintain. Peace out 😎

**Comment by avluis** [comment]
This is a good suggestion, one I would love to implement but a few things will keep it from working properly when it comes to implementing it.
But do know that the 'url share' feature is already a thing and will be available for use with once we push out an update enabling it.
