### ISSUE TITLE
Cannot change the downloads folder

### ISSUE THREAD

**Issue by GlitcherWolf** [AVnetWS/Hentoid#115]
Issue Description:
Cannot change the downloads folder. (Possibly only on MM; haven't checked the others)

Expected behavior:
Could change the downloads folder.

Reproduction steps:
Press "Select Downloads Folder"
Select any other folder
Press "SELECT"
Press "Select Downloads Folder" again and it is the same folder before selecting in the top bar

Additional info:
Version: 1.2.0-beta
Android 6.0.1
Note 4 (N910T)

**Comment by avluis** [comment]
Is this issue based of the current master or an older build?

**Comment by avluis** [comment]
Addressed: 28dc4b8
