### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by M5hizzle** [AVnetWS/Hentoid#118]
**Note:** Be sure to include a **title and clear description**, as much relevant information as possible, and an **executable test case** demonstrating the expected behavior that is not occurring - please delete this paragraph before submitting this issue.

### Issue Description:
Please describe the issue here as best as you can - include snapshots, bug reports or anything else you believe may assist us. If have a file to submit but are concerned for personal data, please [mention](https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-users-and-teams) @AVnetWS/admin-team in this issue for more info.

### Expected behavior:
If you are aware of what the expected behavior should be, please write so in this area, otherwise, replace this text with: Unknown.

### Actual behavior:
How does the application currently behave/respond to the above issue.

### Reproduction steps:
Please describe, in detail, what steps where taken when the issue was apparent, and if possible, if you are able to reproduce it consistently.

### Additional info:
This is required!
Write down your device model, Android version and application version.
Application version is found on the about screen.

**Comment by M5hizzle** [comment]
Your androidmanifest.xml is broken

<manifest platformBuildVersionCode="24" package="me.devsaki.hentoid" versionCode="39" versionName="1.2.0r1" platformBuildVersionName="N">
<uses-sdk minSdkVersion="15" targetSdkVersion="24">
</uses-sdk>
<uses-permission name="android.permission.INTERNET">
</uses-permission>
<uses-permission name="android.permission.ACCESS_NETWORK_STATE">
</uses-permission>
<uses-permission name="android.permission.READ_EXTERNAL_STORAGE">
</uses-permission>
<uses-permission name="android.permission.WRITE_EXTERNAL_STORAGE">
</uses-permission>
<uses-permission name="android.permission.VIBRATE">
</uses-permission>
<uses-permission name="android.permission.WAKE_LOCK">
</uses-permission>

The permission should have been this though....

<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="22"/> <uses-permission android:name="android.permission.INTERNET"/> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android:name="android.permission.WAKE_LOCK"/> <uses-permission android:name="android.permission.VIBRATE" android:maxSdkVersion="18"/>

When i installed 1.2.0 it was stuck at the first manifest,downgraded to 1.1.6 and it changed to the second one.

**Comment by M5hizzle** [comment]
Wtf

**Comment by M5hizzle** [comment]
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="22"/> <uses-permission android:name="android.permission.INTERNET"/> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android:name="android.permission.WAKE_LOCK"/> <uses-permission android:name="android.permission.VIBRATE" android:maxSdkVersion="18"/>

**Comment by M5hizzle** [comment]
My paste is missing

**Comment by M5hizzle** [comment]
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="22"/> <uses-permission android:name="android.permission.INTERNET"/> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android:name="android.permission.WAKE_LOCK"/> <uses-permission android:name="android.permission.VIBRATE" android:maxSdkVersion="18"/>

**Comment by avluis** [comment]
@M5hizzle Can I get a comment as to why this issue was opened and closed so quickly?

**Comment by M5hizzle** [comment]
For some reason,my copy paste post was not visible to me,and hentoid 1.2 gets write permission denied since i tried everythng and failed,pls help?

**Comment by M5hizzle** [comment]
Initializing library,then error write permission denied.

**Comment by M5hizzle** [comment]
@avluis pls respond

**Comment by avluis** [comment]
@M5hizzle GitHub is not an instant reply service -- nor do I do this full time, so if you want me to be able to respond a lot quicker, join the Discord server.

As for your issue -- since you ignored what is required on the very first post, I have no idea what device you are using or anything of the sort.
Please fill in the details, or join the Discord server for faster response.
