### ISSUE TITLE
v1.2 Causes my phone to freeze

### ISSUE THREAD

**Issue by DireOwlbear** [AVnetWS/Hentoid#119]
Ever since i upgraded from 1.1.6 to 1.2 starting a download causes my phone to slow down by a huge amount and even freeze so i have to reset by removing the battery.

First of all imma just go ahead and tell you my phone is a POS and its probably just the app using more recourses than before and if you can't fix it i understand and ill just rollback and not update. Anyways here are my specs, if you need any other info i can try and get it as well.

Manufacturer	Coolpad
Model	5560S
Android version	4.4.2; 0551538; SDK19
CPU	2 cores; Qualcomm MSM8610 msm8610; Max: 1190.4 MHz; Min: 300.0 MHz
Display	800 x 480; DPI: 213; Evaluated Size: 4.4"
Touch screen	Multitouch 5 points
GPU	Adreno (TM) 305; Qualcomm; OpenGL ES-CM 1.1; OpenGL ES 3.0 V@66.0 AU@04.04.02.048.037 (CL@3304448)
RAM	429 MB
Flash	4 GB (3.641 GB actual) (see memory map tab)

**Comment by avluis** [comment]
I would have loved it if you would had followed the format provided when creating this issue, as you have all the information already there, but with a bit of missing info -- the purpose of that template is simple, so I don't have to ask every OP the same question again and again:
What version of Hentoid do you have installed? 1.2 is not a complete version number unfortunately.

As for the resources thing -- you should join us on Discord as I am working on improving downloads and your device would be perfect to test with if it is having issues with downloads -- as this will give me a bottom barrel performance threshold to try and keep to.

**Comment by DireOwlbear** [comment]
Sorry i've never used github before and i don't so a format to follow anywhere...

But anyways v1.2.0r2 is the one causing crashes though i skipped over Hentoid v1.2.0r1 so i'm not sure if it would work.  and ill join the discord server since i already have it downloaded.

**Comment by avluis** [comment]
Closing, as it is fairly similar to #120 -- please reply in that issue thread if additional details are asked of.
