### ISSUE TITLE
Cannot open any of the websites without the app crashing.

### ISSUE THREAD

**Issue by Soupkitten** [AVnetWS/Hentoid#125]
When I tap on any of the websites, the app will wait a second before crashing. This happens on every single site and even after restarting.

This is on the Nexus 6p on Android Nougat, specifically after sideloading the factory images. The version is 1.2.0r3, but other versions have not been tested.

**Comment by Soupkitten** [comment]
Chrome 53 was sideloaded, so that fucked things up.

**Comment by avluis** [comment]
Is this no longer an issue?
Has Google released the factory images yet, I happen to got upgraded via the test program via ota.

**Comment by Soupkitten** [comment]
Not an issue anymore. Me sideloading the latest chrome version screwed things up. Nougat nor the app were at fault.

**Comment by avluis** [comment]
Got it -- thanks for the heads up.
