### ISSUE TITLE
Pururin.us

### ISSUE THREAD

**Issue by Zaroz** [AVnetWS/Hentoid#135]
I know that previously the pururin domain expired and support was dropped in the app, but pururin.us has sprung up to take its place. I believe that you may have to do a bit of coding to download from it as I have never been able to get the "Download" button to work on this site. (I have always had to download via 3rd party apps)

**Hentoid Version**:

**Device/Android Version**:

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by avluis** [comment]
This is not an issue so please do not add this here.
If you really want this, join our Discord Server and explain why yet another source needs to be added.
