### ISSUE TITLE
it Crash on it's own

### ISSUE THREAD

**Issue by Blackheart8788** [AVnetWS/Hentoid#136]
**Hentoid Version**: 1.2.1r2

**Device/Android Version**: Huawei G7

**Issue details / Repro steps**: After setting the app, I start downloading books and if i close the app after or while downloading the books it will crash if i open it again.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by avluis** [comment]
Logcat pls

**Comment by Blackheart8788** [comment]
how can I get the logcat from the app??? i'm not a android dev.

**Comment by Recchan** [comment]
You don't have to be an android dev to get a logcat. You could use adb to get a logcat or you could even use an app like aLogCat or CatLog to do it within android.

**Comment by Blackheart8788** [comment]
ok let me check
