### ISSUE TITLE
Cannot view Fakku subscriptions

### ISSUE THREAD

**Issue by link2110** [AVnetWS/Hentoid#42]
Logged in, subscribed, cannot view on reader, but works in web browser. Cannot download either, it will only download the first page.

Affects version 1.1.2

**Comment by avluis** [comment]
Support for Fakku subscriptions is not currently planned but depending on demand, it could be implemented.
Would need someone that is subscribed to assist, as I am not.

**Comment by link2110** [comment]
I may be able to help, depending on what you need. Probably planning on staying subscribed.
